version: '3'

dotenv: [".task.env"]

tasks:
  dev:install:
    desc: Install node packages
    cmds:
      - task dev:cli -- npm install

  dev:compile:
    task dev:cli -- node_modules/.bin/tsc

  dev:build:
    desc: Build itkdev-docker-compose-server binary for local testing
    cmds:
      - cmd: 'task dev:cli -- npm run build:macos'
        # https://taskfile.dev/usage/#platform-specific-tasks-and-commands
        platforms: [darwin]
      - cmd: 'task dev:cli -- npm run build'
        platforms: [linux]
    sources:
      - '*.json'
      - 'src/**/*.ts'
    generates:
      - itkdev-docker-compose-server

  dev:cli:
    desc: Performs command inside container. Expects parameter(s).
    cmds:
      - docker compose run --rm node {{.CLI_ARGS}}

  build:
    desc: Build linux-x64 for production
    cmds:
      - task dev:cli -- npm run build

  test:run:
    desc: Build binary and run it
    deps: [dev:build]
    cmds:
      - |
        rm .env.docker.local
        ./itkdev-docker-compose-server --debug
      - |
        echo -n > .env.docker.local
        ./itkdev-docker-compose-server --debug
      - |
        echo "COMPOSE_FILES=docker-compose.yml" > .env.docker.local
        ./itkdev-docker-compose-server --debug
      - ./itkdev-docker-compose-server --docker $(which docker) --debug
      - ./itkdev-docker-compose-server --docker $(which docker) config
      - ./itkdev-docker-compose-server --docker $(which docker) run --rm node node --version
