on:
  push:
    tags:
      - '*.*.*'

name: Test build

permissions:
  contents: write

env:
  COMPOSE_USER: runner

jobs:
  test-create-release:
    runs-on: ubuntu-latest
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer install
        run: |
          docker network create frontend
          docker compose run --rm node npm install
          docker compose run --rm node npm run build

      - name: Create checksum
        run: |
          cd ../assets
          sha256sum itkdev-docker-compose-server > ../assets/checksum.txt

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
            name: upload-assets
            path: |
                assets
            retention-days: 7
